### ISSUE TITLE
Мерцание цифр 

### ISSUE THREAD

**Issue by ggvthu766** [DetSimen/TM1637#1]
Мерцание цифр в любом режиме работы. Не зависит от источника питания. Что может быть?

**Comment by DetSimen** [comment]
Либо кривой код, либо неисправный модуль, третьего не дано.

**Comment by DetSimen** [comment]
попробуй. подключи к ногам 5 и 6 и запусти это
 
TM1637 Display(5, 6);
 
void setup(void) {
    Display.SetBrightness(5);
 
disp:
    for (uint16_t i = 1111; i < 10000; i += 1111) {
        Display.Print(i);
        delay(1000);
    }
    goto disp;
}
 
void loop() {
}
 
Мерцает?

**Comment by ggvthu766** [comment]
Спасибо, сейчас разобрался в вопросе. Дело было в delay.
За библиотеку лайк.
